# Copyright (c) 2020 Dongkyu Kim (dkkim1005@gmail.com)

IF (NOT TRNG4_FOUND)

# Setting default paths
IF (NOT TRNG4_INCLUDE_DIR)
  SET (TRNG4_INCLUDE_DIR /usr/local/include)
ENDIF (NOT TRNG4_INCLUDE_DIR)
MESSAGE (STATUS "TRNG4_INCLUDE_DIR : ${TRNG4_INCLUDE_DIR}")
IF (NOT TRNG4_LIBRARY_DIR)
  SET (TRNG4_LIBRARY_DIR /usr/local/lib/)
ENDIF (NOT TRNG4_LIBRARY_DIR)
MESSAGE (STATUS "TRNG4_LIBRARY_DIR : ${TRNG4_LIBRARY_DIR}")

# Check whether header files are in TRNG4_INCLUDE_DIR or not.
MESSAGE (STATUS "Checking for trng4")
SET (HEADER_FILES "yarn5.hpp; uniform01_dist.hpp; uniform_int_dist.hpp")
FOREACH (HEADER_FILE ${HEADER_FILES})
  MESSAGE (STATUS "  Looking for ${HEADER_FILE}")
  FIND_PATH (HEADER_FILE_PATH NAMES ${HEADER_FILE} HINTS "${TRNG4_INCLUDE_DIR}/trng")
  IF (HEADER_FILE_PATH)
	MESSAGE (STATUS "  Looking for ${HEADER_FILE} - found")
  ELSE ()
    MESSAGE (FATAL_ERROR "  ${HEADER_FILE} is not detected.")
  ENDIF (HEADER_FILE_PATH)
ENDFOREACH ()

# Check library
FIND_LIBRARY (TRNG4_LIBRARY_DIR NAMES trng4 libtrng4 HINTS ${TRNG4_LIBRARY_DIR})
IF (TRNG4_LIBRARY_DIR)
  MESSAGE (STATUS "TRNG4 library found")
ELSE()
  MESSAGE (FATAL_ERROR "  Library trng4 is not detected.")
ENDIF (TRNG4_LIBRARY_DIR)

# final
SET (TRNG4_FOUND TRUE)
INCLUDE_DIRECTORIES (SYSTEM ${TRNG4_INCLUDE_DIR})
LINK_DIRECTORIES(${TRNG4_LIBRARY_DIR})
SET (TRNG4_LIBRARIES "trng4")
ENDIF (NOT TRNG4_FOUND)
